import asyncio
import urllib.parse

import httpx

from .models import AuditSession, PatchProposal


class GitHubIntegrationError(Exception):
    pass

async def create_github_pr(session: AuditSession, patch: PatchProposal, github_token: str) -> str:
    """
    Forks the repository, commits the patch, and opens a draft PR.
    Returns the PR URL.
    """
    if not session.repo_path.startswith("http"):
        # For local repos, we can't fork/PR. Return a mock URL for the demo.
        return "https://github.com/demo-user/local-repo/pull/1"

    parsed = urllib.parse.urlparse(session.repo_path)
    path_parts = parsed.path.strip("/").split("/")
    if len(path_parts) < 2:
        raise GitHubIntegrationError("Invalid GitHub URL")
    
    owner, repo = path_parts[0], path_parts[1]
    if repo.endswith(".git"):
        repo = repo[:-4]

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    async with httpx.AsyncClient() as client:
        # 1. Get user login
        user_resp = await client.get("https://api.github.com/user", headers=headers)
        if user_resp.status_code != 200:
            raise GitHubIntegrationError(f"GitHub Auth failed: {user_resp.text}")
        username = user_resp.json()["login"]

        # 2. Fork repo
        fork_resp = await client.post(f"https://api.github.com/repos/{owner}/{repo}/forks", headers=headers)
        if fork_resp.status_code not in (202, 200):
            raise GitHubIntegrationError(f"Failed to fork: {fork_resp.text}")
        
        # Wait a moment for fork to complete
        await asyncio.sleep(2)

        # 3. Get default branch ref
        ref_url_main = f"https://api.github.com/repos/{username}/{repo}/git/refs/heads/main"
        ref_resp = await client.get(ref_url_main, headers=headers)
        if ref_resp.status_code != 200:
            ref_url_master = f"https://api.github.com/repos/{username}/{repo}/git/refs/heads/master"
            ref_resp = await client.get(ref_url_master, headers=headers)
        if ref_resp.status_code != 200:
            raise GitHubIntegrationError("Could not find default branch (main/master).")
        
        base_sha = ref_resp.json()["object"]["sha"]
        branch_name = f"sentinel-patch-{patch.patch_id[:8]}"

        # 4. Create new branch
        branch_resp = await client.post(
            f"https://api.github.com/repos/{username}/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha}
        )
        if branch_resp.status_code != 201:
            raise GitHubIntegrationError(f"Failed to create branch: {branch_resp.text}")

        # 5. Create Tree
        tree_items = []
        for file_patch in patch.files:
            tree_items.append({
                "path": file_patch.file_path,
                "mode": "100644",
                "type": "blob",
                "content": file_patch.patched
            })
            
        tree_resp = await client.post(
            f"https://api.github.com/repos/{username}/{repo}/git/trees",
            headers=headers,
            json={"base_tree": base_sha, "tree": tree_items}
        )
        if tree_resp.status_code != 201:
            raise GitHubIntegrationError(f"Failed to create tree: {tree_resp.text}")
        new_tree_sha = tree_resp.json()["sha"]

        # 6. Create Commit
        commit_resp = await client.post(
            f"https://api.github.com/repos/{username}/{repo}/git/commits",
            headers=headers,
            json={
                "message": f"Security patch: {patch.rationale[:50]}...",
                "tree": new_tree_sha,
                "parents": [base_sha]
            }
        )
        if commit_resp.status_code != 201:
            raise GitHubIntegrationError(f"Failed to create commit: {commit_resp.text}")
        new_commit_sha = commit_resp.json()["sha"]

        # 7. Update Ref
        await client.patch(
            f"https://api.github.com/repos/{username}/{repo}/git/refs/heads/{branch_name}",
            headers=headers,
            json={"sha": new_commit_sha}
        )
        
        # 8. Create PR
        pr_body = (
            f"## Project Sentinel - Security Remediation\n\n"
            f"This PR was auto-generated by Sentinel after an autonomous audit.\n\n"
            f"### Patch Details\n"
            f"**Rationale:** {patch.rationale}\n"
            f"**Risk Level:** {patch.risk}\n\n"
            f"### Diff\n"
            f"```diff\n{patch.unified_diff}\n```\n"
        )
        
        pr_resp = await client.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": f"Security Fix: {patch.rationale[:50]}",
                "body": pr_body,
                "head": f"{username}:{branch_name}",
                "base": "main", # Or dynamically extracted default branch
                "draft": True
            }
        )
        if pr_resp.status_code != 201:
            # Maybe default branch is master
            pr_resp = await client.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers=headers,
                json={
                    "title": f"Security Fix: {patch.rationale[:50]}",
                    "body": pr_body,
                    "head": f"{username}:{branch_name}",
                    "base": "master",
                    "draft": True
                }
            )
            if pr_resp.status_code != 201:
                raise GitHubIntegrationError(f"Failed to create PR: {pr_resp.text}")

        return pr_resp.json()["html_url"]
