import datetime

from .models import AuditSession, FindingCategory


def generate_markdown_report(session: AuditSession) -> str:
    lines = []
    lines.append("# Project Sentinel - Compliance & Remediation Report")
    lines.append(f"**Session ID:** `{session.session_id}`")
    lines.append(f"**Repository:** `{session.repo_path}`")
    lines.append(f"**Generated:** {datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Status:** {session.status.value.upper()}")
    lines.append("")
    
    lines.append("## Executive Summary")
    lines.append(f"Sentinel identified **{len(session.findings)}** potential vulnerabilities. "
                 f"**{len(session.patches)}** patches were generated and validated in the sandbox.")
    if session.approved_patch_id:
        lines.append(f"Patch `{session.approved_patch_id}` was **APPROVED** and applied.")
    lines.append("")
    
    lines.append("## Findings & OWASP Mapping")
    lines.append("| ID | Severity | Category | CWE | OWASP Top 10 | File |")
    lines.append("|---|---|---|---|---|---|")
    
    for finding in session.findings:
        owasp = "A03:2021-Injection" if finding.category == FindingCategory.INJECTION else \
                "A08:2021-Software and Data Integrity Failures" if finding.category == FindingCategory.DESERIALIZATION else \
                "A07:2021-Identification and Authentication Failures" if finding.category == FindingCategory.SECRET else \
                "A01:2021-Broken Access Control"
        
        lines.append(f"| `{finding.rule_id}` | {finding.severity} | {finding.category} | {finding.cwe} | {owasp} | `{finding.file_path}:{finding.line}` |")
        
    lines.append("")
    
    lines.append("## Remediation Evidence (Critic Sign-off)")
    if session.patches:
        patch = session.patches[-1]
        lines.append(f"**Patch ID:** `{patch.patch_id}`")
        lines.append(f"**Risk:** {patch.risk}")
        lines.append(f"**Confidence:** {patch.engineer_confidence:.2f}")
        lines.append("")
        lines.append("### Rationale")
        lines.append(f"> {patch.rationale}")
        lines.append("")
        lines.append("### Unified Diff")
        lines.append("```diff")
        lines.append(patch.unified_diff)
        lines.append("```")
    else:
        lines.append("No patches generated.")
        
    lines.append("")
    lines.append("---")
    lines.append("*Report automatically generated by Project Sentinel Swarm Intelligence.*")
    
    return "\n".join(lines)
