from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from sentinel.agents import CriticAgent, EngineerAgent
from sentinel.models import (
    CodeChunk,
    EvidencePackage,
    Finding,
    FindingCategory,
    FindingSeverity,
    ValidationAxis,
    ValidationAxisStatus,
    ValidationResult,
    Verdict,
    sha256_text,
)


class FakeLLMProvider:
    @property
    def is_available(self) -> bool:
        return True

    @property
    def provider_name(self) -> str:
        return "fake"

    def complete(self, *, system: str, prompt: str, max_tokens: int = 2048):
        class Completion:
            text = (
                '{"patched_file":"import json\\n\\ndef load_user(data):\\n    return json.loads(data)\\n",'
                '"rationale":"Replace pickle with JSON for untrusted payloads.",'
                '"confidence":0.81,'
                '"risk_level":"LOW",'
                '"reasoning":"The diff replaces unsafe deserialization with JSON parsing.",'
                '"required_followup":"Confirm callers pass JSON strings."}'
            )
            model = "fake-model"
            provider = "fake"

        return Completion()


class AgentLLMTest(unittest.TestCase):
    def test_engineer_uses_llm_for_unsupported_deterministic_patch(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            repo = Path(temp_dir)
            target = repo / "loader.py"
            original = "import pickle\n\ndef load_user(data):\n    return pickle.loads(data)\n"
            target.write_text(original, encoding="utf-8")
            finding = Finding(
                rule_id="python.insecure_deserialization.pickle",
                title="Pickle deserialization can execute attacker-controlled code",
                category=FindingCategory.DESERIALIZATION,
                severity=FindingSeverity.CRITICAL,
                file_path="loader.py",
                line=4,
                snippet="return pickle.loads(data)",
                confidence=0.9,
                cwe="CWE-502",
                remediation="Replace pickle with a safe structured format.",
            )
            evidence = EvidencePackage(
                task_id="task_1",
                finding=finding,
                related_chunks=[
                    CodeChunk(
                        chunk_id="chunk_1",
                        file_path="loader.py",
                        start_line=1,
                        end_line=4,
                        text=original,
                        token_fingerprint=sha256_text("chunk_1"),
                    )
                ],
                related_symbols=[],
                graph_neighbors=[],
                static_scan_count=1,
            )

            patch = EngineerAgent(FakeLLMProvider()).propose_patch(
                repo_root=repo,
                evidence=evidence,
                iteration=1,
            )

            self.assertIn("json.loads", patch.files[0].patched)
            self.assertIn("Generated by llm:fake", patch.rationale)

    def test_critic_uses_llm_risk_commentary_when_available(self) -> None:
        patch = type(
            "Patch",
            (),
            {
                "patch_id": "patch_1",
                "files": [],
                "unified_diff": "- pickle.loads(data)\n+ json.loads(data)",
            },
        )()
        validation = ValidationResult(
            task_id="task_1",
            patch_id="patch_1",
            verdict=Verdict.APPROVE,
            axes=[
                ValidationAxis(
                    name="tests",
                    status=ValidationAxisStatus.PASS,
                    detail="All tests passed",
                )
            ],
            exit_code=0,
            stdout="",
            stderr="",
            passing_tests=1,
            total_tests=1,
            resolved_findings=1,
            total_findings=1,
            duration_ms=1,
        )

        risk = CriticAgent(FakeLLMProvider()).risk_assessment(patch=patch, validation=validation)

        self.assertEqual(risk["provider"], "fake")
        self.assertEqual(risk["risk_level"], "LOW")
